### ISSUE TITLE
Add GitHub releases to download links

### ISSUE THREAD

**Issue by legofahrrad** [streetcomplete/streetcomplete-website#1]
Comparing [StreetComplete/streetcomplete/README.md](https://github.com/streetcomplete/StreetComplete/blob/master/README.md#download) and [StreetComplete website](https://streetcomplete.app/?lang=en), the website offers Google Play Store and F-Droid for downloading SC only, whereas the README links to the GitHub releases as well.

---

| ![grafik](https://user-images.githubusercontent.com/92865620/198871645-26a1adb0-ca68-4fa0-9166-bc4970ea26e5.png)<br>README links all three download ways | ![grafik](https://user-images.githubusercontent.com/92865620/198871649-7c4e6a76-2a72-4ecc-a268-f5e3459047df.png)<br>Website links the both app stores only and forgets to mention GitHub releases |
|:-:|:-:|

**Comment by westnordost** [comment]
That's deliberate. It wraps uglily on desktop browser with a third item, plus I do not really recommend the github version (for dummies / for people who do not closely follow the development on github) because it never updates.

**Comment by westnordost** [comment]
Or actually, it does update, through google play, but only if you have google play installed. I think. But then, you can just take the one from google play right away.
